version: "3.9"

services:
    meilisearch:
        image: getmeili/meilisearch:v1.9.0
        container_name: meilisearch
        ports:
            - "127.0.0.1:7700:7700"
        volumes:
            - ./data.ms:/data.ms
        environment:
            - MEILI_NO_ANALYTICS=false
            - MEILI_ENV=${MEILI_ENV:-development}
            - MEILI_LOG_LEVEL
            - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
            - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-m@dkFD3*s4Lo}
