version: "3.9"

services:
    mysql:
        container_name: mysql
        image: mysql:8.4.0
        volumes:
            - ./mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=jamtronic
            - MYSQL_USER=jamtronic
            - MYSQL_PASSWORD=jampass
        restart: always

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - "9200:9200"
        volumes:
            - ./esdata:/usr/share/elasticsearch/data

    redisjam:
        image: redis:6.2
        container_name: redisjam
        ports:
            - "6389:6379"
        restart: always

    backendjam:
        build: ./code
        container_name: backendjam
        volumes:
            - ./code:/var/www
        ports:
            - "8500:80"
        depends_on:
            - mysql
            - redisjam
        env_file:
            - ./code/.env

    workerjamq:
        container_name: workerjamq
        build: ./code
        command: php artisan queue:listen
        volumes:
            - ./code:/var/www
        depends_on:
            - backendjam
        env_file:
            - ./code/.env

    workerjams:
        container_name: workerjams
        build: ./code
        command: php artisan schedule:work
        volumes:
            - ./code:/var/www
        depends_on:
            - backendjam
        env_file:
            - ./code/.env
